// Generated by npm run build. Do not edit by hand.


// server/src/installer.ts
import { open, readFile, rename, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { randomUUID } from "node:crypto";
var VARIABLE = "BITRIX24_WEBHOOK_BASE_URL";
var MAX_RESPONSE_BYTES = 1e6;
var MAX_INPUT_BYTES = 4096;
var InstallerError = class extends Error {
  code;
  constructor(code, message) {
    super(message);
    this.name = "InstallerError";
    this.code = code;
  }
};
function parseWebhookBaseUrl(raw) {
  const value = raw.trim();
  if (!value) {
    throw new InstallerError(
      "EMPTY_WEBHOOK",
      "Webhook \u043D\u0435 \u0432\u0432\u0435\u0434\u0451\u043D, \u0430 \u0441\u043E\u0445\u0440\u0430\u043D\u0451\u043D\u043D\u043E\u0439 \u043A\u043E\u043D\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u0438 \u043D\u0435\u0442."
    );
  }
  if (Buffer.byteLength(value, "utf8") > MAX_INPUT_BYTES) {
    throw new InstallerError("INVALID_WEBHOOK", "Webhook \u0432\u044B\u0433\u043B\u044F\u0434\u0438\u0442 \u0441\u043B\u0438\u0448\u043A\u043E\u043C \u0434\u043B\u0438\u043D\u043D\u044B\u043C.");
  }
  let url;
  try {
    url = new URL(value);
  } catch {
    throw new InstallerError("INVALID_WEBHOOK", "\u042D\u0442\u043E \u043D\u0435 \u043F\u043E\u0445\u043E\u0436\u0435 \u043D\u0430 URL webhook Bitrix24.");
  }
  if (url.protocol !== "https:") {
    throw new InstallerError("INVALID_WEBHOOK", "Webhook \u0434\u043E\u043B\u0436\u0435\u043D \u043D\u0430\u0447\u0438\u043D\u0430\u0442\u044C\u0441\u044F \u0441 https://.");
  }
  if (url.username || url.password || url.search || url.hash) {
    throw new InstallerError(
      "INVALID_WEBHOOK",
      "\u0412 webhook \u043D\u0435 \u0434\u043E\u043B\u0436\u043D\u043E \u0431\u044B\u0442\u044C \u043B\u043E\u0433\u0438\u043D\u0430 \u0432 \u0430\u0434\u0440\u0435\u0441\u0435, \u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440\u043E\u0432 \u043F\u043E\u0441\u043B\u0435 ? \u0438\u043B\u0438 \u0444\u0440\u0430\u0433\u043C\u0435\u043D\u0442\u0430 \u043F\u043E\u0441\u043B\u0435 #."
    );
  }
  if (!/^\/rest\/[1-9][0-9]*\/[A-Za-z0-9_-]+\/?$/u.test(url.pathname)) {
    throw new InstallerError(
      "INVALID_WEBHOOK",
      "\u041E\u0436\u0438\u0434\u0430\u0435\u0442\u0441\u044F \u043F\u043E\u043B\u043D\u044B\u0439 \u0432\u0445\u043E\u0434\u044F\u0449\u0438\u0439 webhook \u0432\u0438\u0434\u0430 https://\u043F\u043E\u0440\u0442\u0430\u043B/rest/ID/\u0421\u0415\u041A\u0420\u0415\u0422."
    );
  }
  url.pathname = url.pathname.replace(/\/+$/u, "");
  return url;
}
async function boundedJson(response) {
  const announced = Number(response.headers.get("content-length") ?? "0");
  if (announced > MAX_RESPONSE_BYTES) {
    throw new InstallerError("RESPONSE_TOO_LARGE", "Bitrix24 \u0432\u0435\u0440\u043D\u0443\u043B \u0441\u043B\u0438\u0448\u043A\u043E\u043C \u0431\u043E\u043B\u044C\u0448\u043E\u0439 \u043E\u0442\u0432\u0435\u0442.");
  }
  if (!response.body) {
    throw new InstallerError("INVALID_RESPONSE", "Bitrix24 \u0432\u0435\u0440\u043D\u0443\u043B \u043F\u0443\u0441\u0442\u043E\u0439 \u043E\u0442\u0432\u0435\u0442.");
  }
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let bytes = 0;
  let text = "";
  for (; ; ) {
    const { value, done } = await reader.read();
    if (done) break;
    bytes += value.byteLength;
    if (bytes > MAX_RESPONSE_BYTES) {
      await reader.cancel();
      throw new InstallerError("RESPONSE_TOO_LARGE", "Bitrix24 \u0432\u0435\u0440\u043D\u0443\u043B \u0441\u043B\u0438\u0448\u043A\u043E\u043C \u0431\u043E\u043B\u044C\u0448\u043E\u0439 \u043E\u0442\u0432\u0435\u0442.");
    }
    text += decoder.decode(value, { stream: true });
  }
  text += decoder.decode();
  try {
    const parsed = JSON.parse(text);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      throw new Error("not an object");
    }
    return parsed;
  } catch {
    throw new InstallerError(
      "INVALID_RESPONSE",
      "\u0421\u0435\u0440\u0432\u0435\u0440 \u043E\u0442\u0432\u0435\u0442\u0438\u043B \u043D\u0435 \u0432 \u0444\u043E\u0440\u043C\u0430\u0442\u0435 Bitrix24 REST. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u0430\u0434\u0440\u0435\u0441 webhook."
    );
  }
}
function upstreamMessage(code, method) {
  if (code === "NO_AUTH_FOUND" || code === "INVALID_CREDENTIALS") {
    return "Bitrix24 \u043D\u0435 \u043F\u0440\u0438\u043D\u044F\u043B webhook. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u0430\u0434\u0440\u0435\u0441 \u0438\u043B\u0438 \u0441\u043E\u0437\u0434\u0430\u0439\u0442\u0435 \u043D\u043E\u0432\u044B\u0439 \u0432\u0445\u043E\u0434\u044F\u0449\u0438\u0439 webhook.";
  }
  if (code === "ACCESS_DENIED" || code === "INSUFFICIENT_SCOPE") {
    return method === "profile" ? "Webhook \u043F\u0440\u0438\u043D\u044F\u0442, \u043D\u043E \u0443 \u0435\u0433\u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F \u043D\u0435\u0434\u043E\u0441\u0442\u0430\u0442\u043E\u0447\u043D\u043E \u043F\u0440\u0430\u0432." : "Webhook \u0440\u0430\u0431\u043E\u0442\u0430\u0435\u0442, \u043D\u043E \u0435\u043C\u0443 \u043D\u0435 \u0432\u044B\u0434\u0430\u043D \u0434\u043E\u0441\u0442\u0443\u043F \u043A \u0437\u0430\u0434\u0430\u0447\u0430\u043C. \u0414\u043E\u0431\u0430\u0432\u044C\u0442\u0435 \u043F\u0440\u0430\u0432\u043E \xAB\u0417\u0430\u0434\u0430\u0447\u0438\xBB \u0432 Bitrix24.";
  }
  if (code === "QUERY_LIMIT_EXCEEDED" || code === "OPERATION_TIME_LIMIT") {
    return "Bitrix24 \u0432\u0440\u0435\u043C\u0435\u043D\u043D\u043E \u043E\u0433\u0440\u0430\u043D\u0438\u0447\u0438\u043B \u0437\u0430\u043F\u0440\u043E\u0441\u044B. \u041F\u043E\u0434\u043E\u0436\u0434\u0438\u0442\u0435 \u043C\u0438\u043D\u0443\u0442\u0443 \u0438 \u043F\u043E\u0432\u0442\u043E\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0430\u043D\u043E\u0432\u043A\u0443.";
  }
  return `Bitrix24 \u043E\u0442\u043A\u043B\u043E\u043D\u0438\u043B \u043F\u0440\u043E\u0432\u0435\u0440\u043A\u0443 (${code.slice(0, 80)}).`;
}
async function call(baseUrl, method, fetchImpl, timeoutMs) {
  const url = new URL(baseUrl);
  url.pathname = `${url.pathname}/${method}.json`;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  let response;
  try {
    response = await fetchImpl(url, {
      method: "POST",
      headers: { accept: "application/json", "content-type": "application/json" },
      body: "{}",
      redirect: "manual",
      signal: controller.signal
    });
  } catch (error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      throw new InstallerError("TIMEOUT", "Bitrix24 \u043D\u0435 \u043E\u0442\u0432\u0435\u0442\u0438\u043B \u0437\u0430 10 \u0441\u0435\u043A\u0443\u043D\u0434.");
    }
    throw new InstallerError(
      "NETWORK_ERROR",
      "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u043F\u043E\u0434\u043A\u043B\u044E\u0447\u0438\u0442\u044C\u0441\u044F \u043A Bitrix24. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u0441\u0435\u0442\u044C, DNS \u0438 TLS \u043D\u0430 \u0441\u0435\u0440\u0432\u0435\u0440\u0435 Iva."
    );
  } finally {
    clearTimeout(timer);
  }
  if (response.status >= 300 && response.status < 400) {
    throw new InstallerError("REDIRECT_REFUSED", "Webhook \u043F\u0435\u0440\u0435\u043D\u0430\u043F\u0440\u0430\u0432\u043B\u044F\u0435\u0442 \u0437\u0430\u043F\u0440\u043E\u0441 \u043D\u0430 \u0434\u0440\u0443\u0433\u043E\u0439 \u0430\u0434\u0440\u0435\u0441.");
  }
  const envelope = await boundedJson(response);
  const rawCode = typeof envelope.error === "string" ? envelope.error : void 0;
  const code = rawCode && /^[A-Z0-9_]{1,80}$/u.test(rawCode) ? rawCode : void 0;
  if (!response.ok || rawCode) {
    throw new InstallerError(
      code ?? (response.ok ? "UPSTREAM_ERROR" : `HTTP_${response.status}`),
      code ? upstreamMessage(code, method) : response.ok ? "Bitrix24 \u043E\u0442\u043A\u043B\u043E\u043D\u0438\u043B \u043F\u0440\u043E\u0432\u0435\u0440\u043A\u0443 \u0431\u0435\u0437 \u0431\u0435\u0437\u043E\u043F\u0430\u0441\u043D\u043E\u0433\u043E \u043A\u043E\u0434\u0430 \u043E\u0448\u0438\u0431\u043A\u0438." : `Bitrix24 \u0432\u0435\u0440\u043D\u0443\u043B HTTP ${response.status}.`
    );
  }
  if (!("result" in envelope)) {
    throw new InstallerError("INVALID_RESPONSE", "\u0412 \u043E\u0442\u0432\u0435\u0442\u0435 Bitrix24 \u043E\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 result.");
  }
}
async function probeWebhook(raw, options = {}) {
  const url = parseWebhookBaseUrl(raw);
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  const timeoutMs = options.timeoutMs ?? 1e4;
  await call(url, "profile", fetchImpl, timeoutMs);
  await call(url, "tasks.task.getFields", fetchImpl, timeoutMs);
  return url.toString();
}
async function readConfiguredWebhook(envPath) {
  let source;
  try {
    source = await readFile(envPath, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
  for (const line of source.split("\n")) {
    const match = /^BITRIX24_WEBHOOK_BASE_URL=(.*)$/u.exec(line);
    if (match?.[1]) return match[1].trim();
  }
  return null;
}
async function writeWebhookAtomic(envPath, normalized) {
  const temporary = join(dirname(envPath), `.bitrix24-read.env-${randomUUID()}.tmp`);
  const file = await open(temporary, "wx", 384);
  try {
    await file.writeFile(`${VARIABLE}=${normalized}
`, "utf8");
    await file.sync();
  } finally {
    await file.close();
  }
  try {
    await rename(temporary, envPath);
  } catch (error) {
    await rm(temporary, { force: true });
    throw error;
  }
}

// server/src/installer-main.ts
async function readStdin() {
  const chunks = [];
  let bytes = 0;
  for await (const chunk of process.stdin) {
    const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
    bytes += buffer.byteLength;
    if (bytes > 4096) throw new Error("\u0412\u0432\u0435\u0434\u0451\u043D\u043D\u043E\u0435 \u0437\u043D\u0430\u0447\u0435\u043D\u0438\u0435 \u0441\u043B\u0438\u0448\u043A\u043E\u043C \u0434\u043B\u0438\u043D\u043D\u043E\u0435.");
    chunks.push(buffer);
  }
  return Buffer.concat(chunks).toString("utf8").trim();
}
async function main() {
  const envPath = process.argv[2];
  if (!envPath) throw new Error("\u041D\u0435 \u0443\u043A\u0430\u0437\u0430\u043D \u043F\u0443\u0442\u044C \u043A\u043E\u043D\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u0438 \u043F\u043B\u0430\u0433\u0438\u043D\u0430.");
  const entered = await readStdin();
  const raw = entered || await readConfiguredWebhook(envPath);
  if (!raw) throw new Error("Webhook \u043D\u0435 \u0432\u0432\u0435\u0434\u0451\u043D, \u0430 \u0441\u043E\u0445\u0440\u0430\u043D\u0451\u043D\u043D\u043E\u0439 \u043A\u043E\u043D\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u0438 \u043D\u0435\u0442.");
  const normalized = await probeWebhook(raw);
  await writeWebhookAtomic(envPath, normalized);
  console.log("\u2713 Webhook \u043F\u0440\u0438\u043D\u044F\u0442, \u0434\u043E\u0441\u0442\u0443\u043F \u043A \u043F\u0440\u043E\u0444\u0438\u043B\u044E \u0438 \u0437\u0430\u0434\u0430\u0447\u0430\u043C \u043F\u0440\u043E\u0432\u0435\u0440\u0435\u043D.");
  console.log("\u2713 \u041A\u043E\u043D\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044F \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0430 \u0441 \u0437\u0430\u043A\u0440\u044B\u0442\u044B\u043C\u0438 \u043F\u0440\u0430\u0432\u0430\u043C\u0438.");
}
main().catch((error) => {
  const message = error instanceof Error ? error.message : "\u041D\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043D\u0430\u044F \u043E\u0448\u0438\u0431\u043A\u0430 \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438.";
  console.error(`\u2717 ${message}`);
  process.exitCode = 1;
});
