import { mkdir, readFile, writeFile } from "node:fs/promises";
import { build } from "esbuild";

const entries = [
  { input: "server/src/main.ts", output: "plugin/server.mjs" },
  { input: "server/src/installer-main.ts", output: "plugin/setup.mjs" },
];

await mkdir("plugin", { recursive: true });
await mkdir("tmp", { recursive: true });
const metadata = {};
for (const entry of entries) {
  const result = await build({
    entryPoints: [entry.input],
    outfile: entry.output,
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node24",
    sourcemap: false,
    legalComments: "eof",
    metafile: true,
    banner: {
      js: "// Generated by npm run build. Do not edit by hand.\n",
    },
  });
  const bundled = await readFile(entry.output, "utf8");
  await writeFile(entry.output, bundled.replace(/[ \t]+$/gmu, ""));
  Object.assign(metadata, result.metafile.outputs);
}

await writeFile(
  "tmp/bundle-meta.json",
  `${JSON.stringify({ outputs: metadata }, null, 2)}\n`,
);
