import { mkdir, readFile, writeFile } from "node:fs/promises";
import { build } from "esbuild";

const output = "plugin/server.mjs";

await mkdir("plugin", { recursive: true });
await mkdir("tmp", { recursive: true });
const result = await build({
  entryPoints: ["server/src/main.ts"],
  outfile: output,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node24",
  sourcemap: false,
  legalComments: "eof",
  metafile: true,
  banner: {
    js: "// Generated by npm run build. Do not edit by hand.\n",
  },
});

const bundled = await readFile(output, "utf8");
await writeFile(output, bundled.replace(/[ \t]+$/gmu, ""));

await writeFile(
  "tmp/bundle-meta.json",
  `${JSON.stringify(result.metafile, null, 2)}\n`,
);
